In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
from datasets import load_dataset
from sklearn.model_selection import train_test_split
import numpy as np
import torch
from torch.utils.data import DataLoader, Dataset
from pathlib import Path
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [2]:
pbc = pd.read_csv('data/pbc2.csv')
ftpred = pd.read_csv('data/ft_db_cbcts_dummy_vit-t_ftdet.csv')

In [54]:
ftpred[(ftpred.subsplit == 'train')].time.max()

47.0

In [4]:
ftpred_train = ftpred[ftpred['subsplit'] == 'train']
ftpred_val = ftpred[ftpred['subsplit'] == 'val']
ftpred_test = ftpred[ftpred['subsplit'] == 'test']

In [37]:
class FTPredDataset(Dataset):
    def __init__(self,
                 df: pd.DataFrame,
                 crop_or_pad_to: int = 30,
                 transforms = None):
        self.df = df
        self.transform = transforms
        self.groups = [g for _, g in self.df.groupby("id")]
        self.crop_or_pad_to = crop_or_pad_to

    def __len__(self):
        return len(self.groups)

    def __getitem__(self, idx):
        sample = self.groups[idx]

        if self.transform:
            sample = self.transform(sample)
        X = sample.drop(columns=["event", "event_at_time", "time", "start", "stop", "id", "split", "subsplit"]).values
        X = self.get_padded_features(X)
        Y = (sample['time'] - sample['stop']).values[-1] # get last
        D = sample['event_at_time'].values[-1] # get last
        return X, Y, D

    def get_padded_features(self, x):
        """Helper function to pad variable length RNN inputs with nans."""
        d = self.crop_or_pad_to
        difference = d - len(x)
        if difference < 0:
            return x[:d]
        pads = np.nan*np.ones((difference,) + x.shape[1:])
        return np.concatenate([x, pads])

class AugmentTimeVaryingSurvivalFeatures:
    def __init__(self,
                 only_censored_samples: bool = False,
                 probability: float = 0.5):
        self.rng = np.random.default_rng()
        self.only_censored_samples = only_censored_samples
        self.probability = probability

    def __call__(self, x: pd.DataFrame) -> pd.DataFrame:
        total_samples = len(x)
        if total_samples <= 1:
            return x
        if self.only_censored_samples and (1 in x['event_at_time'].unique()):
            return x
        # only sample with a certain probability
        if self.rng.random() > self.probability:
            return x
        new_length = self.rng.integers(1, total_samples)
        new_sample = x.iloc[:new_length].copy()
        return new_sample

In [46]:
train_data = FTPredDataset(ftpred_train) #, transforms=AugmentTimeVaryingSurvivalFeatures())
val_data = FTPredDataset(ftpred_val)
test_data = FTPredDataset(ftpred_test)

In [49]:
x, y, d = train_data[0]
print(x.shape, y, d)

(30, 192) 0.0 0

In [40]:
train_data.groups[0]

,id,start,stop,event,split,subsplit,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_12,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,feature_25,feature_26,feature_27,feature_28,feature_29,feature_30,feature_31,feature_32,feature_33,feature_34,feature_35,feature_36,feature_37,feature_38,feature_39,feature_40,feature_41,feature_42,feature_43,feature_44,feature_45,feature_46,feature_47,feature_48,feature_49,feature_50,feature_51,feature_52,feature_53,feature_54,feature_55,feature_56,feature_57,feature_58,feature_59,feature_60,feature_61,feature_62,feature_63,feature_64,feature_65,feature_66,feature_67,feature_68,feature_69,feature_70,feature_71,feature_72,feature_73,feature_74,feature_75,feature_76,feature_77,feature_78,feature_79,feature_80,feature_81,feature_82,feature_83,feature_84,feature_85,feature_86,feature_87,feature_88,feature_89,feature_90,feature_91,feature_92,feature_93,feature_94,feature_95,feature_96,feature_97,feature_98,feature_99,feature_100,feature_101,feature_102,feature_103,feature_104,feature_105,feature_106,feature_107,feature_108,feature_109,feature_110,feature_111,feature_112,feature_113,feature_114,feature_115,feature_116,feature_117,feature_118,feature_119,feature_120,feature_121,feature_122,feature_123,feature_124,feature_125,feature_126,feature_127,feature_128,feature_129,feature_130,feature_131,feature_132,feature_133,feature_134,feature_135,feature_136,feature_137,feature_138,feature_139,feature_140,feature_141,feature_142,feature_143,feature_144,feature_145,feature_146,feature_147,feature_148,feature_149,feature_150,feature_151,feature_152,feature_153,feature_154,feature_155,feature_156,feature_157,feature_158,feature_159,feature_160,feature_161,feature_162,feature_163,feature_164,feature_165,feature_166,feature_167,feature_168,feature_169,feature_170,feature_171,feature_172,feature_173,feature_174,feature_175,feature_176,feature_177,feature_178,feature_179,feature_180,feature_181,feature_182,feature_183,feature_184,feature_185,feature_186,feature_187,feature_188,feature_189,feature_190,feature_191,time,event_at_time
0,2247,0.0,1.0,0,train,train,-0.068892,0.434450,-0.475962,-0.606508,-1.107826,-0.516562,-1.426366,0.924110,0.315815,-0.290152,0.467812,-0.617799,0.011929,0.252888,-0.596915,-2.849330,-0.217827,-0.302398,-0.464257,-1.775085,-0.320602,0.488962,0.287560,0.725694,0.648309,0.507853,0.326476,0.390315,0.444491,-1.348959,-0.185466,-0.416936,-0.906970,2.383559,-0.072003,0.112769,1.149105,-0.427800,-0.142462,-0.311258,-0.000711,-0.463965,0.156178,-0.153701,0.546417,-0.743221,-0.392014,0.522309,0.502649,-0.439763,-0.502359,-0.240684,-0.155769,0.510055,-1.249786,-0.208171,-0.649825,-1.271306,0.293010,-0.122519,0.425848,-0.656036,-1.035086,0.024229,-0.415100,0.247042,0.736095,0.457277,1.118314,-0.138723,0.603962,-0.034964,1.124289,-0.190289,-1.545760,-0.392904,-0.180932,1.205222,1.606579,1.354515,0.790959,-0.042253,0.043080,-0.538366,-0.282173,-0.090835,0.142220,0.532247,0.345122,-0.325657,-0.896765,0.117699,0.725369,-0.416583,-0.971546,-0.040033,1.464501,0.603989,1.123547,-0.499343,-0.098019,-0.428140,0.989843,-0.371760,0.552297,0.497693,-1.010880,0.157130,-0.293085,0.245201,-0.332840,0.536084,-0.582569,-0.604443,0.712304,-0.183913,0.283048,0.711450,-0.356052,-0.125031,-0.060907,-0.543221,0.496483,-0.380315,-0.635010,-0.036659,0.059456,0.572905,0.005715,-0.704481,-0.274242,-1.866201,1.047939,0.329890,0.249523,0.297566,-0.600154,-0.381039,-1.452676,-1.021666,0.249725,-0.013913,0.199483,-0.499990,-0.072221,-0.370190,0.582528,-0.187887,0.454385,0.486713,-0.337155,-1.497586,-0.138716,-1.087387,-0.318607,-1.145454,-1.118870,0.556388,0.471356,-0.732965,0.355277,-0.643899,-0.403243,0.419948,-0.356891,0.862359,-0.191525,0.443402,0.466493,-0.576038,0.681238,0.377939,0.412992,0.011536,-0.091395,0.205965,9.901992,-0.355886,-0.866850,-0.393897,-0.288230,1.313411,0.041764,1.423958,0.524819,-0.328623,-0.417134,0.811602,-0.452318,-0.576654,-0.047882,0.395285,35.0,0
1,2247,1.0,2.0,0,train,train,-0.717001,0.220855,-1.223452,-0.179500,-0.808897,-1.077805,-1.336015,0.257365,-0.722389,-0.146704,0.563405,-0.334192,0.226545,0.530657,-0.843811,-2.032294,-0.304053,-0.313681,-0.496503,-1.068051,-0.202947,0.406830,-0.023849,0.535094,0.135429,0.475412,0.192433,-0.097791,1.196582,-1.098957,-0.471318,-0.291723,-0.410339,1.849719,-0.555330,0.114793,0.727206,-0.457571,-0.224443,-0.581863,0.480472,-0.576977,0.793992,-0.164734,0.131095,-0.623867,-0.053744,-0.427979,0.177386,-0.172219,-0.441008,-0.197504,-0.165824,-0.382235,-1.117448,0.276416,-0.523685,-0.512743,-0.079642,-0.158801,-0.654009,-0.616159,-0.490714,-0.340945,-0.067155,-0.074229,0.209070,-0.245588,1.073804,0.142481,0.492907,-0.361029,0.669569,0.205171,0.280137,1.118742,-0.137691,0.522233,1.865619,1.042860,0.801490,0.241039,-0.301661,-0.827377,-0.627668,-0.562636,0.734826,1.099021,0.458537,-0.773585,-0.474658,0.022075,0.565852,-0.269307,-1.199796,0.215035,1.748761,-0.043269,0.881726,-0.851839,0.469456,0.051965,0.750912,0.304742,1.196217,1.093974,-0.271917,-0.345449,-0.516488,0.222943,0.074896,0.428228,-0.308981,-0.383139,0.676804,-0.498367,0.479777,0.842400,0.133280,-0.206368,-0.306191,0.339053,0.272274,-0.211573,-0.294875,0.105247,-0.632950,0.483333,0.215709,-0.808862,-1.062912,-1.890046,0.574194,0.702411,0.356910,0.503599,-0.292838,-0.212069,-1.613549,-0.248654,-0.047126,-0.267881,-0.306299,-0.550974,-0.484585,-0.061039,1.107658,0.008921,-0.102992,0.262115,0.229179,-1.225505,0.343473,-0.579576,0.102610,-0.709508,-0.350399,0.088230,0.367253,-1.046256,-0.374953,0.183695,-0.606180,0.386982,0.054552,0.371508,-0.238172,0.347625,0.779522,-0.741001,0.359868,0.009226,0.813055,0.130396,-0.222624,0.296102,10.527724,-1.126358,-1.611939,0.217558,-0.305494,0.696388,-0.407239,0.793590,-0.073133,-0.289788,-0.196773,1.107303,-0.944761,-0.058083,0.102993,-0.078859,35.0,0
2,2247,2.0,3.0,0,train,train,-0.263348,0.303479,-0.918676,-0.392439,-0.879700,-0.781503,-1.255901,0.564914,0.400822,-0.234287,0.416643,-0.437310,-0.038832,0.167407,-0.748181,-3.197802,-0.451166,0.035956,-0.364591,-1.752061,-0.328480,0.475103,0.409276,0.450915,0.542860,0.679526,0.406566,0.190534,0.374117,-1.087977,-0.222218,-0.285588,-0.708703,1.888041,-0.119056,0.229274,0.893532,-0.568592,-0.206012,-0.446943,0.231803,-0.526115,0.553487,-0.340016,0.497036,-0.839560,-0.493206,0.247275,0.457468,-0.508879,-0.433910,-0.130110,-0.167351,0.034367,-0.927601,-0.361034,-0.160152,-1.027624,0.088303,0.088705,0.104379,-0.946570,-0.672495,-0.104312,-0.171619,0.039645,0.490565,0.113877,1.238630,-0.016717,0.801086,-0.108255,0.558274,-0.205482,-1.091204,0.070783,-0.095615,1.144874,1.716486,1.229409,0.880611,0.353063,-0.043196,-0.922158,-0.186884,-0.267610,0.483997,0.335198,0.542064,-0.756801,-0.844879,0.263588,0.546577,-0.265409,-1.238306,-0.068540,1.532813,0.331757,1.119287,-0.552460,0.336102,-0.334176,1.133708,-0.073406,0.998188,0.672545,-0.617232,-0.070972,-0.518303,-0.014192,-0.096196,0.531886,-0.456161,-0.594498,0.363557,-0.201170,0.309180,0.941494,0.175017,-0.187059,-0.003670,-0.405063,0.427317,-0.435693,-0.639893,0.489164,-0.171498,0.309716,0.014699,-0.928958,-0.400144,-2.211341,0.753526,0.539444,0.454346,0.351734,-0.432689,-0.327053,-1.949342,-0.862149,0.262447,0.237340,-0.211783,-0.862043,-0.162372,-0.175245,0.661588,-0.058003,0.097881,0.195997,-0.042387,-0.977972,-0.022347,-0.668385,-0.324137,-0.816110,-1.103547,0.643971,0.603913,-0.569546,-0.058193,-0.110749,-0.779779,0.363410,-0.110890,0.919518,-0.344650,0.190430,0.593651,-0.541073,0.280545,0.253234,0.468815,0.134229,-0.487871,0.050924,10.143761,-0.325607,-1.173190,0.016498,0.114143,1.110235,0.057042,1.287820,0.344738,-0.824365,-0.325366,1.067182,-0.314858,-0.459070,0.092862,0.424478,35.0,0
3,2247,3.0,4.0,0,train,train,-0.332103,0.431307,-0.862906,-0.554698,-1.210610,-0.708795,-1.497685,0.813009,-0.012032,-0.018277,0.658643,-0.500518,0.077240,0.515022,-0.757015,-2.174532,-0.670614,-0.438302,-0.424990,-1.483061,-0.098793,0.486185,0.496677,0.419077,0.439637,0.256994,0.318480,-0.037349,0.634984,-1.312833,-0.253808,-0.394735,-0.662961,1.813993,-0.823067,0.188032,0.905807,-0.574182,-0.467189,-0.469473,0.275770,-0.480886,0.434839,-0.083309,0.474365,-0.752760,-0.706760,0.244131,0.622523,-0.398464,-0.527278,-0.320272,-0.151150,-0.193221,-1.213860,-0.253736,-0.682894,-0.676480,0.265441,0.294298,0.072941,-0.805709,-0.939632,-0.028191,-0.180364,0.156025,0.547457,0.197327,1.305061,-0.077836,0.728280,-0.026203,0.647296,0.026415,-0.643137,0.524889,-0.329846,1.164034,1.624720,1.464824,0.683077,0.390690,0.033847,-0.823077,-0.123754,-0.194156,0.543673,0.697615,0.215648,-0.574967,-0.920605,0.137139,0.608993,-0.212842,-1.262425,0.181908,1.700356,0.339043,1.191302,-0.359981,0.016189,-0.271897,0.812609,0.275511,0.612794,0.688757,-0.603057,-0.242229,-0.645673,0.243870,-0.108240,0.512541,-0.537789,-0.825574,0.249378,-0.334307,0.486986,0.801898,0.199520,0.208599,-0.126511,0.103746,0.626052,-0.411869,-0.567756,0.188780,0.030466,0.706882,-0.083374,-0.558481,-0.334820,-2.109607,1.016038,0.398866,0.309925,0.062448,-0.628732,-0.188757,-1.824430,-0.821154,0.059623,0.042761,0.003942,-1.002764,-0.393283,-0.205293,1.079684,0.053806,0.286989,0.131705,0.003602,-1.833637,0.080990,-0.780467,-0.085321,-0.861791,-0.955811,0.414374,0.370160,-1.138582,-0.336042,-0.056514,-0.802548,0.115288,-0.291330,1.103329,-0.161286,0.508311,0.605705,-0.342129,0.272995,-0.012513,0.478839,0.135183,-0.383543,0.227345,10.075923,-0.684676,-1.317415,-0.183844,-0.311585,1.326210,-0.220094,1.243602,0.768744,-0.250556,-0.319306,0.972536,-0.478428,-0.342993,0.131308,0.365132,35.0,0
4,2247,4.0,7.0,0,train,train,-0.457872,0.643610,-1.109912,-0.527613,-1.161993,-0.853324,-1.861990,0.871819,-0.445282,0.140382,0.557849,-0.705521,0.216399,0.705868,-0.776322,-1.788551,-0.463163,-0.426956,-0.643634,-1.173014,-0.352682,0.332448,0.295609,0.506543,0.215165,0.360302,0.414237,0.258729,1.100274,-1.106760,-0.347667,-0.424817,-0.683829,1.970202,-1.011346,0.082775,1.016325,-0.297992,-0.203243,-0.183771,0.250889,-0.423025,0.595931,-0.180616,0.689085,-0.735305,-0.467380,0.144708,0.285987,-0.324858,-0.517019,-0.539927,-0.152469,-0.303647,-1.466371,-0.139826,-0.764608,-0.406096,0.073074,0.389422,-0.155189,-0.674510,-0.688207,-0.175109,-0.202200,0.087121,0.754886,-0.100164,1.034123,-0.212652,0.590208,-0.113125,0.825447,0.276369,-0.325245,0.791935,-0.305719,0.999753,1.571821,1.360768,0.775251,0.247687,-0.025973,-0.767043,-0.355563,-0.391109,0.472218,0.832877,0.171666,-0.591222,-0.459662,0.199856,0.471791,-0.421775,-1.539700,0.182115,1.769006,0.220784,0.961002,-0.298777,0.194430,-0.140318,0.667888,0.395622,0.822132,1.023898,-0.334268,-0.333851,-0.632290,0.275723,-0.091591,0.512833,-0.343865,-0.744719,0.295013,-0.270344,0.479814,0.830298,0.337254,-0.076472,0.002484,-0.104595,0.405939,-0.613981,-0.123145,0.106919,-0.159745,0.634646,-0.282219,-0.517992,-0.881469,-1.943888,1.250994,0.782213,0.529033,-0.061562,-0.635370,-0.400777,-1.886548,-0.516087,-0.114972,-0.227060,-0.017397,-0.890381,-0.531819,-0.219554,1.316368,-0.067698,0.119941,0.355133,0.197129,-1.630491,0.390698,-0.503696,-0.304652,-1.065979,-0.886887,0.463641,0.139269,-1.396299,-0.382367,0.016815,-0.782927,0.253313,-0.014746,0.722377,-0.260167,0.486500,0.545940,-0.523041,0.156004,0.091855,0.521660,-0.003950,-0.074623,0.315680,10.031436,-0.918014,-1.454298,0.014724,-0.283012,1.170183,-0.117416,1.153386,0.392975,-0.131262,-0.353377,0.893180,-0.718563,-0.281935,0.285350,0.186047,35.0,0
5,2247,7.0,8.0,0,train,train,0.095534,0.414280,-0.501918,-0.575590,-0.929408,-0.724534,-1.505989,0.513744,0.659122,-0.200145,0.303283,-0.557598,0.284999,0.188932,-0.231466,-3.395268,-0.284070,-0.517347,-0.637861,-1.685920,-0.519146,0.711559,0.559791,0.512693,0.614836,0.323584,0.456452,0.158941,0.084742,-1.182388,-0.254016,-0.294223,-0.768880,2.201452,0.077448,0.118748,0.847012,-0.691980,-0.339442,-0.045107,0.090347,-0.538886,0.151786,-0.187396,0.542929,-0.752464,-0.377483,0.540280,0.456492,-0.344675,-0.588317,-0.322545,-0.211188,0.454817,-1.496544,-0.346190,-0.502415,-1.202603,0.240744,0.190362,0.351999,-0.658544,-0.853132,-0.185052,-0.220767,0.505740,0.874775,0.681074,1.402292,0.017781,0.704968,-0.225428,0.777065,-0.073066,-1.882107,-0.155130,-0.232957,1.374328,1.397700,1.467042,0.625425,0.243673,0.288880,-0.367102,-0.078281,-0.167268,0.024933,0.594234,0.379542,-0.473450,-0.806164,0.079557,0.963430,-0.222584,-0.813351,0.002931,1.867619,0.582018,1.406265,-0.262559,-0.301548,-0.534229,1.028180,-0.473594,0.406603,0.297259,-1.210223,0.162267,-0.246533,0.098410,-0.376684,0.286721,-0.840675,-0.780945,0.633027,0.004224,0.397292,0.759886,-0.357623,-0.118069,-0.165687,-0.638816,0.496920,-0.122662,-0.802724,0.214298,-0.063242,0.347573,-0.178712,-0.756534,-0.452309,-1.711556,0.673929,0.348924,0.069520,0.330765,-0.520151,-0.138497,-1.625477,-0.645585,0.234359,0.002995,0.085575,-0.208251,0.034675,-0.253670,0.360448,-0.205605,0.335659,0.178177,-0.057480,-1.284471,-0.415243,-0.845676,-0.147467,-0.846383,-1.203506,0.627535,0.460683,-0.832774,0.454789,-0.521743,-0.135701,0.173570,-0.673529,1.101581,-0.174902,0.402875,0.505630,-0.706076,0.430040,0.508909,0.414881,-0.131138,-0.437896,0.157822,9.656413,-0.030088,-1.018508,-0.464311,-0.283434,1.600505,0.091973,1.445687,0.854292,-0.122182,-0.465421,0.733594,-0.521376,-0.915274,0.127429,0.409583,35.0,0
6,2247,8.0,9.0,0,train,train,0.027188,0.356952,-0.629225,-0.567204,-1.117985,-0.644327,-1.697666,0.694404,0.342989,-0.156377,0.136287,-0.643474,0.444910,0.359228,-0.423048,-2.971601,-0.340570,-0.616521,-0.574464,-1.884989,-0.500240,0.719563,0.599809,0.429116,0.671960,0.163894,0.469791,0.065829,0.358708,-1.241319,-0.295839,0.015483,-0.725243,2.504922,-0.162349,0.213608,0.971628,-0.444729,-0.255584,-0.240088,-0.002986,-0.410453,0.273150,-0.073253,0.548251,-0.775209,-0.650153,0.371581,0.548018,-0.318183,-0.472113,-0.427448,-0.219165,0.197879,-1.288273,-0.302900,-0.698719,-0.950507,0.271569,0.276988,0.349156,-0.812051,-0.923576,-0.006922,-0.422854,0.312500,0.963243,0.235618,1.239213,0.228318,0.591386,-0.160906,1.028926,-0.047349,-1.653013,-0.206917,-0.287312,1.111868,1.374328,1.528926,0.962456,0.348235,0.173375,-0.420302,-0.086299,-0.345365,0.431408,0.556484,0.412567,-0.053088,-0.850360,-0.083875,0.585520,-0.173423,-1.001522,0.021036,1.902472,0.649108,0.916143,-0.097323,-0.152579,-0.232135,0.874219,-0.127882,0.617975,0.389812,-1.046786,0.345614,-0.443598,0.339264,-0.278462,0.532367,-0.550911,-0.986068,0.584556,0.205288,0.408422,0.780256,-0.121657,0.002810,-0.096789,-0.617694,0.158653,-0.323440,-0.912102,0.216589,-0.081159,0.560425,-0.445067,-0.668236,-0.555511,-1.804238,0.686182,0.327254,0.109704,0.210453,-0.565552,-0.252896,-1.674052,-0.664525,-0.000198,0.188294,0.139020,-0.640114,-0.104422,-0.204888,0.579342,-0.479623,0.402795,0.096641,-0.189249,-1.289434,-0.133617,-1.227665,-0.054079,-1.107940,-1.091847,0.717799,0.434294,-0.998304,0.250621,-0.308344,-0.534920,-0.138360,-0.493392,1.128020,-0.095033,0.418899,0.640647,-0.597716,0.567427,0.406573,0.427403,0.018910,-0.280732,0.343796,9.673496,-0.307164,-0.942438,-0.497305,-0.366813,1.512762,-0.114049,1.382878,1.005303,-0.202119,-0.452989,0.727837,-0.555615,-0.599229,0.195267,0.399890,35.0,0
7,2247,9.0,10.0,0,train,train,-1.273514,0.574268,-0.962366,-0.165176,-0.912034,-1.010404,-1.536326,0.615677,-0.459276,0.315897,0.608535,-1.068213,-0.077902,0.970885,-1.400033,-1.428543,-0.130067,-0.774075,-0.482801,-0.917111,0.204663,0.295745,0.470982,0.172168,0.417431,0.641093,0.208222,0.231555,1.250627,-1.461033,-0.119328,-0.571716,-0.541242,1.523744,-0.907497,0.211475,0.880758,-0.402898,-0.416971,-0.289864,0.282897,-0.365489,0.624398,-0.114464,0.218237,-0.739336,0.181092,-0.245425,0.430964,-0.301745,-0.593378,-0.172389,-0.455283,0.058921,-1.187970,0.002764,-0.560255,-0.420243,-0.084819,0.424046,-0.536325,-0.527139,-1.005880,-0.464721,-0.027040,0.353873,0.491258,0.056790,0.731142,0.180521,0.443564,0.010853,0.964788,0.406467,-0.231418,1.675619,-0.635731,0.854066,2.193327,1.140458,0.762172,0.004085,0.009469,-0.373951,-0.767390,-0.527364,0.697317,1.231756,0.296629,-0.754273,-0.621421,0.450927,0.486300,-0.578442,-1.330908,-0.194596,2.274940,-0.443710,1.125424,-0.654452,-0.254344,-0.045161,0.612160,-0.108605,0.672509,0.722238,-0.435632,-0.278528,-0.113645,0.407573,-0.142421,0.140098,-0.550341,-0.354231,0.585631,-0.779381,0.588969,0.536046,-0.515829,-0.259247,-0.329510,0.059278,0.720157,-0.507028,-0.062473,-0.292702,-0.673939,0.686481,0.319350,-0.461250,-1.158838,-1.274828,1.415178,0.557910,0.317455,0.135474,-0.012749,-0.561353,-1.207059,-0.561901,0.026653,0.069836,-0.147212,-0.416904,-0.412615,-0.029807,1.000612,0.413843,0.043257,0.280728,0.236651,-1.825850,0.412753,-0.452040,-0.034803,-0.990694,-0.342143,-0.161154,-0.001209,-1.193949,-0.173764,0.119223,-0.258211,0.444643,0.150543,-0.116502,0.076125,0.078578,0.182480,-0.456127,0.533700,-0.199265,0.547938,0.006207,0.008078,0.559026,10.157218,-0.897790,-1.046250,-0.177379,-0.345741,0.724434,-0.351015,1.054200,-0.550573,0.027214,-0.316170,0.459156,-1.305606,-0.019929,0.287820,0.350317,35.0,0
8,2247,10.0,14.0,0,train,train,-1.040699,0.568736,-0.979637,-0.238607,-0.806480,-1.129204,-1.734557,0.490589,-0.425110,0.330255,0.582453,-0.848630,0.254648,0.784978,-1.108763,-1.306994,-0.104109,-0.916370,-0.640739,-0.701585,-0.071988,0.228459,0.222556,0.497301,0.219472,0.539531,0.379874,0.202372,1.180228,-1.255904,-0.149320,-0.398574,-0.189828,1.464063,-0.940867,0.072200,0.963448,-0.353490,-0.233839,-0.473058,0.361960,-0.366483,0.998666,-0.175488,0.457718,-0.560922,-0.099564,-0.315622,0.009613,-0.241258,-0.530779,-0.187129,-0.383698,-0.090999,-1.288484,0.263083,-0.434110,-0.140338,-0.019527,0.268183,-0.285319,-0.507292,-0.763739,-0.289922,-0.064791,0.476592,0.286315,-0.377387,1.093480,-0.127765,0.434320,-0.081498,0.885665,0.578341,0.120081,1.735767,-0.561148,0.854043,1.491823,1.065871,0.888166,0.311177,-0.090117,-0.339370,-0.779258,-0.865674,0.371895,1.187250,0.336869,-0.486681,-0.380937,0.070704,0.716151,-0.638264,-1.515685,0.141744,1.933150,-0.344287,1.076516,-0.264193,-0.205781,-0.023441,0.639923,0.055076,0.666138,0.807218,-0.512948,-0.468753,-0.434274,0.471348,-0.287172,0.100165,-0.422214,-0.394242,0.415007,-0.525327,0.577812,0.650310,-0.362642,-0.317104,-0.341987,0.013555,0.230128,-0.745709,0.005228,0.037222,-0.497465,0.652376,0.227393,-0.381821,-1.233980,-1.090709,1.331786,0.497254,0.285478,0.127271,-0.322900,-0.618303,-1.617779,-0.207263,-0.001289,-0.014157,-0.355080,-0.811170,-0.582003,-0.102563,1.025323,0.417085,0.190358,0.467306,0.063226,-1.805839,0.196158,-0.529765,-0.027440,-0.651430,-0.555852,-0.113184,0.045505,-1.625529,-0.308200,0.290472,-0.371493,0.370425,-0.056250,-0.157914,0.023571,0.227045,0.232558,-0.715187,0.379449,0.038233,0.868968,0.016318,0.061145,0.524668,10.399523,-1.052163,-1.327236,-0.131129,-0.125628,0.874570,-0.355239,0.687736,-0.449314,0.313321,-0.405842,0.737419,-0.823341,-0.035216,0.311788,0.195702,35.0,0

In [50]:
np.isnan(x[:, 0])

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True])

In [55]:
for i in range(len(test_data)):
    x, y, d = test_data[i]
    print(f'{y=}, {d=}')

y=0.0, d=1
y=0.0, d=1
y=0.0, d=1
y=0.0, d=1
y=0.0, d=1
y=0.0, d=1
y=0.0, d=1
y=0.0, d=1
y=0.0, d=1
y=0.0, d=0
y=0.0, d=1
y=0.0, d=1
y=0.0, d=1
y=0.0, d=1
y=0.0, d=0
y=0.0, d=1
y=0.0, d=0
y=0.0, d=1
y=0.0, d=1
y=0.0, d=1
y=0.0, d=1
y=0.0, d=0
y=0.0, d=1
y=0.0, d=0
y=0.0, d=1
y=0.0, d=1
y=0.0, d=1
y=0.0, d=0
y=0.0, d=1
y=0.0, d=0
y=0.0, d=1
y=0.0, d=0
y=0.0, d=1
y=0.0, d=1
y=0.0, d=1
y=0.0, d=1
y=0.0, d=1
y=0.0, d=1
y=0.0, d=1
y=0.0, d=0
y=0.0, d=1
y=0.0, d=0
y=0.0, d=1
y=0.0, d=1
y=0.0, d=1
y=0.0, d=0
y=0.0, d=1
y=0.0, d=1
y=0.0, d=0
y=0.0, d=1
y=0.0, d=0
y=0.0, d=0
y=0.0, d=1
y=0.0, d=1
y=0.0, d=1
y=0.0, d=1
y=0.0, d=1

In [43]:
val_data.groups[0]

,id,start,stop,event,split,subsplit,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_12,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,feature_25,feature_26,feature_27,feature_28,feature_29,feature_30,feature_31,feature_32,feature_33,feature_34,feature_35,feature_36,feature_37,feature_38,feature_39,feature_40,feature_41,feature_42,feature_43,feature_44,feature_45,feature_46,feature_47,feature_48,feature_49,feature_50,feature_51,feature_52,feature_53,feature_54,feature_55,feature_56,feature_57,feature_58,feature_59,feature_60,feature_61,feature_62,feature_63,feature_64,feature_65,feature_66,feature_67,feature_68,feature_69,feature_70,feature_71,feature_72,feature_73,feature_74,feature_75,feature_76,feature_77,feature_78,feature_79,feature_80,feature_81,feature_82,feature_83,feature_84,feature_85,feature_86,feature_87,feature_88,feature_89,feature_90,feature_91,feature_92,feature_93,feature_94,feature_95,feature_96,feature_97,feature_98,feature_99,feature_100,feature_101,feature_102,feature_103,feature_104,feature_105,feature_106,feature_107,feature_108,feature_109,feature_110,feature_111,feature_112,feature_113,feature_114,feature_115,feature_116,feature_117,feature_118,feature_119,feature_120,feature_121,feature_122,feature_123,feature_124,feature_125,feature_126,feature_127,feature_128,feature_129,feature_130,feature_131,feature_132,feature_133,feature_134,feature_135,feature_136,feature_137,feature_138,feature_139,feature_140,feature_141,feature_142,feature_143,feature_144,feature_145,feature_146,feature_147,feature_148,feature_149,feature_150,feature_151,feature_152,feature_153,feature_154,feature_155,feature_156,feature_157,feature_158,feature_159,feature_160,feature_161,feature_162,feature_163,feature_164,feature_165,feature_166,feature_167,feature_168,feature_169,feature_170,feature_171,feature_172,feature_173,feature_174,feature_175,feature_176,feature_177,feature_178,feature_179,feature_180,feature_181,feature_182,feature_183,feature_184,feature_185,feature_186,feature_187,feature_188,feature_189,feature_190,feature_191,time,event_at_time
190,8627,0.0,1.0,0,train,val,-0.859018,-0.177306,-1.163738,0.320626,-1.174936,-1.169593,-0.346020,-0.339829,-0.044220,-0.059034,0.203406,-0.374147,0.173983,1.430195,-1.113985,-1.280219,0.464748,-2.684733,-0.374080,-1.316408,0.112944,-0.449070,0.294957,0.877408,0.481111,0.258377,0.896642,-1.287352,-0.251695,-0.126010,0.024280,0.727466,-0.334345,1.984853,-0.133523,0.746833,-0.147693,-0.830733,-0.069244,-0.372449,0.479776,-1.238468,0.758744,-0.115445,0.028310,-0.468833,0.013311,-1.140311,0.040105,-0.160757,0.687038,0.844174,-1.434333,-0.315567,0.536281,-0.288848,-0.384523,-1.484845,-0.104346,1.382517,0.070386,-0.878728,0.308806,-0.618762,0.464111,0.440040,0.428460,-0.614283,0.889544,0.413472,-0.228066,-0.055612,0.133410,-0.065442,-0.063663,0.604300,-1.424404,-0.452750,1.731072,0.726786,1.031908,0.907635,-0.108849,-0.174023,-0.533426,-1.253023,0.729307,1.665406,0.249445,-0.063060,-1.011266,-0.013548,0.621338,-0.470537,-0.822636,0.198597,1.989948,0.100286,0.895872,-1.143496,-0.799614,1.121794,0.487941,1.020969,0.374867,0.414829,-0.921939,0.024330,-1.016670,-0.297920,0.199856,0.012966,-0.743908,-0.125117,0.649327,0.892691,0.398268,0.696615,0.670353,0.326763,-0.547191,0.013241,0.369417,-0.169768,-0.450168,0.191805,-0.587214,1.605104,-0.452136,-0.178573,-0.605398,-2.045234,0.905912,0.067162,0.549107,0.047516,0.447382,-0.192406,-1.019897,1.642809,0.446881,0.686994,-0.461478,-0.998399,-0.037673,-0.381670,-0.144790,-0.628971,-0.572485,-0.187470,0.457140,-0.240670,0.373838,-1.670797,0.844585,-0.027137,-0.819803,0.176330,0.017611,-0.450589,-0.141568,0.502160,0.143707,0.426257,-0.716758,-0.034763,0.028764,0.246395,0.504120,-0.234584,-0.274723,-0.044447,0.195279,-0.669354,-0.046672,0.155547,9.264411,-1.955967,-0.845966,-0.354192,-0.140963,0.458668,0.585987,0.241200,-0.844838,-0.971718,0.194920,0.448739,-0.349162,0.348042,0.075012,-0.313611,24.0,1
191,8627,1.0,2.0,0,train,val,-0.818108,-0.149603,-1.378225,0.159409,-1.384015,-1.275517,-0.513550,-0.401073,0.136742,-0.194109,0.046430,-0.663867,0.613711,1.290185,-0.866700,-1.722405,0.268409,-2.275867,-0.337082,-1.448910,-0.237321,-0.431460,0.403003,1.023775,0.872993,0.199232,0.603533,-0.647092,-0.584525,-0.250358,0.068955,0.240638,-0.259659,2.370134,0.097513,0.761145,-0.064419,-1.054887,0.220130,-0.630263,0.002304,-1.290249,0.659405,-0.659422,0.723550,-0.539152,0.079259,-1.156647,-0.572395,0.269217,0.634415,0.834846,-1.527153,0.103427,0.270780,-0.201349,-0.182861,-1.355286,0.265049,1.341581,0.271002,-0.928380,-0.328721,-0.821160,0.430928,0.977209,0.314749,-0.391002,1.044688,0.338803,-0.092276,0.199858,0.477444,0.488357,-0.475166,0.254614,-1.300806,-0.168176,1.446927,0.626493,0.822301,1.144309,0.221629,-0.220789,-0.245084,-1.207041,0.587712,1.052664,0.369271,0.031817,-1.050092,-0.241973,1.290772,-0.361618,-0.389427,-0.243901,2.100386,0.354532,1.129762,-0.588825,-0.631050,0.832911,0.327151,1.425797,0.333961,0.576849,-1.118950,0.107023,-0.944693,-0.570976,0.136777,0.261869,-0.601179,-0.197665,1.005401,1.110904,0.543318,0.840947,0.187441,0.112425,-0.345526,-0.375436,0.674393,-0.338631,0.007652,0.189768,-0.793927,1.552883,-0.536296,-0.266480,-1.355207,-1.476951,1.276366,0.195463,0.268722,-0.041283,0.217194,-0.428907,-1.842644,1.969089,0.787424,0.712341,-0.297785,-1.189397,0.058523,-0.293533,-0.059523,-0.075910,0.012608,0.011087,0.623834,-0.112668,0.253831,-2.115259,0.821073,-0.051314,-1.152848,0.311495,-0.004117,-0.534910,0.128173,0.357346,-0.157643,0.916609,-1.311501,-0.392527,-0.225906,0.285873,0.411169,-0.692622,-0.420072,0.226269,0.436000,-0.925526,0.327484,0.304059,8.645521,-1.430934,-1.458365,-0.527057,-0.112467,0.532145,0.066385,0.172007,-0.644157,-0.433349,-0.154162,0.559455,-0.473803,-0.008943,0.002829,-0.407688,24.0,1
192,8627,2.0,3.0,0,train,val,-0.770405,-0.215152,-1.218940,0.236921,-1.421894,-1.418004,-0.549129,-0.542914,0.060976,-0.233845,0.102919,-0.711375,0.473332,1.354392,-1.073176,-1.430971,0.420862,-2.675701,-0.365159,-1.595273,-0.195224,-0.380731,0.343750,0.812475,0.880588,0.065875,0.647327,-0.952384,-0.538868,-0.362792,0.094338,0.466855,-0.245320,2.490672,0.074806,0.842584,-0.238316,-1.119140,0.108690,-0.634329,0.032910,-1.294650,0.366629,-0.479331,0.548445,-0.681508,-0.067332,-1.206564,-0.380390,0.204840,0.889112,1.089222,-1.540167,0.042597,0.332077,-0.317323,-0.377267,-1.521440,0.104672,1.483684,0.312936,-1.183701,-0.119937,-0.811650,0.379690,0.843468,0.261772,-0.301000,0.986253,0.357560,-0.344643,0.204027,0.314727,0.386690,-0.466230,0.338471,-1.433308,-0.377486,1.531261,0.688217,1.038194,1.162112,0.061125,-0.147067,-0.373661,-0.980118,0.722904,1.352098,0.405219,-0.078452,-0.952379,-0.154658,1.245462,-0.287943,-0.434265,-0.122937,2.140340,0.226805,1.117458,-0.755844,-0.723057,0.987583,0.251857,1.500523,0.426395,0.569181,-1.203982,0.259600,-0.987683,-0.530544,0.248627,0.287088,-0.582638,-0.245970,0.891246,1.260847,0.405720,0.878201,0.291308,0.172733,-0.359876,-0.275424,0.436099,-0.147581,-0.034459,0.417477,-0.782311,1.544746,-0.408056,-0.308687,-1.176682,-1.582765,1.148696,0.035688,0.362091,-0.018251,0.319133,-0.288980,-1.475781,2.220468,1.168091,0.738600,-0.195208,-1.275802,0.067496,-0.202631,-0.125502,-0.097922,-0.182778,-0.053760,0.592063,-0.028507,0.315316,-2.125105,0.940375,0.019435,-1.179239,0.305423,-0.086244,-0.566003,0.050388,0.516863,-0.031605,0.906052,-1.208249,-0.446654,-0.250432,0.223939,0.425340,-0.421039,-0.445344,0.202926,0.172895,-0.626267,0.215876,0.323809,8.213447,-1.732107,-1.420653,-0.611013,-0.068913,0.376264,0.196769,0.153224,-0.748678,-0.431454,0.149420,0.438118,-0.346280,0.225189,0.048050,-0.433105,24.0,1
193,8627,3.0,4.0,0,train,val,-0.911311,-0.460295,-1.463625,0.520963,-1.328839,-1.440041,-0.302853,-0.527926,0.443633,-0.166021,0.114893,-0.260896,0.171366,1.161542,-0.901853,-0.936339,0.624629,-3.163334,-0.202689,-1.323650,0.054935,-0.322916,0.109501,0.830091,0.582232,0.184975,1.140454,-1.274093,-0.227229,-0.426777,0.107123,0.128638,-0.221604,1.512661,0.249505,0.678067,-0.447631,-1.093489,-0.019764,-0.274568,0.925739,-1.553590,0.483082,-0.290661,0.059205,-0.593704,0.093062,-2.012476,-0.414414,-0.163865,0.777448,0.888072,-1.461845,-0.397013,0.592042,-0.326097,0.019246,-1.438132,-0.028467,1.704579,0.349468,-1.366101,0.392047,-0.896322,0.293926,0.617327,-0.027328,-0.632339,0.865464,0.619433,-0.707917,-0.044193,-0.052242,0.132012,0.446909,0.493804,-1.102501,-0.499793,1.482495,0.544183,1.002361,1.009455,-0.330891,0.044420,-0.762137,-1.117062,0.746956,1.847722,0.318737,0.077088,-0.918653,-0.105762,0.926594,-0.081481,-0.772476,0.098478,1.999555,-0.118816,1.007123,-1.087623,-0.875478,1.110561,0.411956,1.238304,0.556825,0.376914,-0.996130,0.008718,-1.010095,0.245272,0.322313,0.152377,-0.693230,-0.077721,0.749037,0.764863,0.372924,1.182811,-0.030821,0.407970,-0.728988,0.428156,0.471796,-0.269775,-0.080207,0.160903,-0.744006,1.884416,-0.483565,-0.335743,-0.876737,-2.054852,1.101259,-0.086497,0.865073,0.227981,0.414372,0.132395,-1.293839,2.585480,0.867672,0.636710,-0.122856,-1.628068,0.177650,-0.210228,0.206130,0.004502,-0.385435,-0.068900,0.481129,0.097968,0.243717,-1.835897,0.779520,0.380698,-1.018013,-0.175632,-0.141084,-0.374010,-0.288285,0.774625,0.277343,0.688677,-1.114336,-0.066338,-0.002870,0.643808,0.346780,-0.633022,-0.586625,0.362550,0.478075,-0.834915,-0.016009,0.470742,7.831392,-2.105490,-0.985289,-0.245720,0.178884,0.510495,0.295225,-0.031120,-1.169510,-0.842215,-0.134154,0.236065,-0.448871,0.755822,0.034730,-0.306659,24.0,1
194,8627,4.0,7.0,0,train,val,-0.866505,-0.337332,-1.425526,0.308579,-1.262359,-1.344296,-0.514249,-0.365216,0.265774,-0.122169,0.144015,-0.435886,0.539997,1.157426,-0.911849,-1.111508,0.463920,-2.615472,-0.384991,-1.194108,-0.088609,-0.362977,0.342068,0.803207,0.700049,0.226542,0.839550,-0.977074,-0.342772,-0.137340,0.139383,0.226452,-0.317374,2.010130,0.177007,0.745544,-0.116943,-1.111354,0.117118,-0.707563,0.544301,-1.280299,0.675857,-0.718649,0.425123,-0.468780,0.183609,-1.547385,-0.530730,-0.156802,0.681180,0.786562,-1.404307,-0.074548,0.434729,-0.150761,-0.034133,-1.495339,0.021236,1.509873,0.129785,-0.984524,0.063037,-0.792735,0.422346,0.751218,0.200192,-0.478313,0.901899,0.485768,-0.279606,0.113017,0.161463,0.143292,0.141670,0.463376,-1.174427,-0.343486,1.364695,0.495684,0.597454,0.913857,-0.106077,-0.091851,-0.595966,-1.220071,0.477708,1.342465,0.257244,0.023338,-0.832999,-0.169686,0.829203,-0.443154,-0.656534,-0.060694,1.970350,0.245431,1.028897,-0.885244,-0.721002,1.018523,0.285752,1.511049,0.478038,0.409551,-0.893389,0.024175,-1.148417,-0.120113,0.122332,0.050157,-0.735455,-0.256039,0.853317,0.911179,0.428416,0.994701,-0.037393,0.285254,-0.580618,0.074953,0.465926,-0.320606,-0.076986,0.197392,-0.717957,1.678239,-0.346788,-0.330633,-1.213428,-1.680235,1.203635,0.064134,0.693211,0.179260,0.358142,-0.302077,-1.487977,2.192266,0.673928,0.477481,-0.352655,-1.317534,0.118259,-0.264864,-0.028361,-0.103665,-0.214209,-0.062048,0.539569,-0.103907,0.240656,-1.769142,0.751827,0.197836,-0.902850,0.095024,-0.224042,-0.594254,-0.076202,0.611251,0.089903,0.665444,-1.174570,-0.053140,-0.070417,0.417556,0.465048,-0.669697,-0.455604,0.196886,0.518942,-0.890313,0.259095,0.520945,8.948320,-1.775910,-1.102888,-0.160017,-0.015537,0.629014,0.236136,0.025433,-1.115981,-0.597798,-0.107659,0.477151,-0.580916,0.400548,0.042017,-0.291331,24.0,1
195,8627,7.0,8.0,0,train,val,-0.819845,-0.155127,-1.287599,0.252535,-1.056165,-1.163808,-0.305828,-0.365646,0.068999,-0.190147,0.113965,-0.328999,0.201033,1.287255,-1.144175,-1.622360,0.487050,-2.654772,-0.447481,-1.175263,-0.074823,-0.387997,0.227031,0.907705,0.574163,0.338478,0.859186,-1.171631,-0.384136,-0.054655,-0.026542,0.616209,-0.230435,1.789369,-0.077252,0.718366,-0.135683,-0.893867,-0.087850,-0.448977,0.436341,-1.274164,0.642978,-0.166315,0.177307,-0.336266,-0.080662,-1.130503,-0.161749,-0.267687,0.712078,0.779297,-1.489238,-0.257635,0.599132,-0.325335,-0.254854,-1.487381,-0.046847,1.373739,0.118913,-1.047317,0.267191,-0.662481,0.361638,0.496220,0.323388,-0.599451,0.841300,0.554047,-0.161771,-0.083523,0.025675,-0.053466,-0.032420,0.551799,-1.371001,-0.161175,1.614634,0.693426,0.932710,0.876968,-0.016786,-0.027889,-0.362204,-1.175260,0.741478,1.496385,0.228482,-0.040402,-1.155309,-0.056377,0.889987,-0.299552,-0.697931,0.173511,1.906624,0.250232,0.943421,-1.054002,-0.809640,0.962063,0.567167,0.972392,0.487173,0.323700,-1.031316,0.082874,-1.040834,-0.368863,0.067175,0.184684,-0.893139,-0.011646,0.723418,0.792563,0.387303,0.736506,0.648753,0.420876,-0.598094,0.059368,0.381053,-0.012580,-0.394874,0.172728,-0.714996,1.638437,-0.495789,-0.192642,-0.691743,-1.885525,0.955727,0.035234,0.671367,0.059352,0.409627,-0.205176,-1.045650,1.665246,0.452958,0.659616,-0.191089,-0.954600,0.003782,-0.366693,-0.130877,-0.593113,-0.628111,-0.254009,0.404954,-0.198085,0.158400,-1.989839,0.886344,0.072869,-0.976337,0.064632,-0.067405,-0.355600,0.011350,0.322437,0.316834,0.404014,-0.844944,0.063721,-0.094449,0.385473,0.467591,-0.369160,-0.359643,0.075214,0.378675,-0.829348,-0.057991,0.159043,9.329094,-1.786384,-0.931520,-0.247390,-0.172848,0.533476,0.609491,0.214406,-0.713103,-0.889555,0.071733,0.646616,-0.360342,0.465475,0.009942,-0.244145,24.0,1
196,8627,8.0,9.0,0,train,val,-0.711709,-0.281802,-1.218520,0.231512,-1.546787,-1.430055,-0.537038,-0.474936,0.114968,-0.261120,0.129215,-0.764178,0.357084,1.331844,-1.052380,-1.475489,0.485945,-2.548444,-0.383463,-1.602941,-0.202242,-0.281432,0.306244,0.921779,0.802068,0.105087,0.661874,-0.897129,-0.471625,-0.252640,0.068933,0.504860,-0.162214,2.588383,0.029979,0.806824,-0.172524,-1.150902,0.069742,-0.587805,0.038764,-1.289919,0.445287,-0.523316,0.507628,-0.655405,-0.034318,-1.143112,-0.444172,0.204086,0.909878,1.182756,-1.644670,0.084951,0.295302,-0.347564,-0.302546,-1.538529,0.125812,1.478161,0.319612,-1.069788,-0.125119,-0.772911,0.428001,0.947562,0.357340,-0.286838,1.053098,0.340339,-0.210912,0.205993,0.169085,0.414458,-0.482117,0.406099,-1.486522,-0.311292,1.541762,0.655831,0.992690,1.056830,0.160095,-0.084675,-0.324030,-1.091026,0.620231,1.217225,0.387410,-0.268166,-0.881985,-0.215818,1.273577,-0.380965,-0.456981,-0.196595,2.131024,0.238915,1.173535,-0.675470,-0.732760,0.958616,0.294871,1.485533,0.388497,0.576139,-1.201040,0.356243,-0.983723,-0.490268,0.123827,0.348797,-0.591337,-0.142257,0.951485,1.098230,0.459486,0.768503,0.340185,0.058492,-0.303380,-0.302463,0.363387,-0.215057,-0.143443,0.379091,-0.763584,1.471258,-0.469900,-0.304932,-1.264233,-1.440530,1.229632,0.094056,0.413820,-0.092304,0.327863,-0.445492,-1.597880,2.198045,1.065265,0.720165,-0.080379,-1.228144,0.126810,-0.322674,-0.123037,-0.145603,-0.289745,-0.118511,0.494582,-0.081246,0.339985,-2.184809,0.920374,0.079502,-1.218145,0.293119,-0.057449,-0.630277,0.103103,0.513161,0.004229,0.966353,-1.216409,-0.556036,-0.168925,0.190893,0.387385,-0.298131,-0.506299,0.226139,0.194590,-0.684217,0.238123,0.221942,8.257298,-1.638087,-1.355099,-0.489687,0.096909,0.383523,0.195670,0.273545,-0.725088,-0.427987,0.140814,0.358083,-0.391156,0.151499,0.107241,-0.486710,24.0,1
197,8627,9.0,10.0,0,train,val,-0.936361,-0.402782,-1.440571,0.432281,-1.344850,-1.186821,-0.230834,-0.405899,0.369748,-0.365350,0.074374,-0.373835,0.235311,1.333353,-1.089816,-1.588831,0.467327,-2.924647,-0.134775,-1.082935,-0.081601,-0.519277,0.127225,1.038252,0.676907,0.108022,0.986604,-1.206908,-0.358856,-0.267597,0.078815,0.246044,-0.255572,1.339797,0.127525,0.677849,-0.574059,-1.071191,-0.069956,-0.424438,0.666197,-1.682624,0.387940,-0.063408,0.298899,-0.430115,-0.196120,-1.637033,-0.272129,0.007001,0.760028,0.881943,-1.468024,-0.326373,0.475549,-0.472428,-0.055917,-1.342150,0.124697,1.518293,0.327530,-1.388557,0.203934,-0.869306,0.376451,0.695885,-0.001090,-0.477646,0.720305,0.590730,-0.421732,-0.022372,-0.103083,0.216060,0.162277,0.559327,-1.005019,-0.426335,1.411197,0.793543,1.231158,1.012791,-0.121573,-0.238860,-0.275287,-1.100494,0.812220,1.603257,0.334271,-0.041474,-1.270457,-0.070063,1.217683,0.038798,-0.612585,0.136623,1.959880,0.077188,1.080474,-0.983984,-0.780990,0.987149,0.421642,1.223417,0.366172,0.297791,-1.126036,-0.112314,-1.022543,-0.079177,0.428208,0.441653,-0.604645,0.028000,0.831671,0.817030,0.440219,1.098166,0.435777,0.487130,-0.705325,0.218420,0.603066,-0.011973,-0.119357,0.071253,-0.903430,1.710953,-0.504161,-0.093843,-0.902696,-1.987802,1.132964,-0.222735,0.564612,-0.008743,0.395425,0.106060,-1.418367,2.275118,0.890928,0.579921,-0.027650,-1.434767,0.262366,-0.259252,-0.048638,-0.091724,-0.493110,-0.061870,0.462955,0.087967,0.158376,-1.943789,0.791297,0.185733,-1.266058,-0.061853,-0.005470,-0.136451,-0.111420,0.460748,-0.041906,0.737082,-1.203480,0.199170,-0.222329,0.557997,0.642996,-0.498244,-0.626558,0.343854,0.464727,-1.007511,-0.105750,0.304599,8.263823,-1.997964,-1.186758,-0.341212,0.169168,0.435539,0.470812,0.127692,-0.684195,-0.919040,-0.104404,0.572836,-0.394755,0.474008,-0.185360,-0.254008,24.0,1
198,8627,10.0,11.0,0,train,val,-0.870988,-0.137452,-1.405394,0.314820,-1.331607,-1.382242,-0.384809,-0.443436,0.327241,-0.305478,0.045294,-0.607550,0.552538,1.261859,-1.017255,-1.669216,0.314951,-2.570084,-0.401199,-1.503076,-0.172082,-0.252281,0.344794,0.890993,0.847915,0.078862,0.540656,-0.941391,-0.642356,-0.334611,0.013537,0.452877,-0.155124,2.376050,0.080850,0.778047,-0.167010,-1.130614,0.057803,-0.524268,0.256310,-1.352583,0.408667,-0.318900,0.488859,-0.442517,-0.089923,-1.227249,-0.479751,0.160122,0.945145,0.984037,-1.408037,-0.030752,0.304754,-0.347137,-0.302597,-1.349574,0.157986,1.324789,0.273436,-1.193639,-0.163249,-0.836376,0.453351,0.827315,0.259399,-0.324347,0.893785,0.377215,-0.168649,0.113793,0.230499,0.458979,-0.372759,0.497858,-1.306267,-0.268621,1.425031,0.745987,0.980023,1.138582,0.078995,-0.267441,-0.335889,-1.022207,0.696480,1.238866,0.286291,-0.105060,-0.892429,-0.214131,1.222307,-0.239078,-0.429178,0.060555,2.058025,0.250618,1.178413,-0.607199,-0.711000,1.048379,0.311870,1.397835,0.426904,0.580724,-1.235816,0.111515,-1.094981,-0.534058,0.234620,0.370469,-0.679411,-0.018687,0.846797,1.179464,0.234025,0.941488,0.242490,0.107742,-0.400967,-0.331114,0.519753,-0.061874,-0.111744,0.187966,-0.787761,1.474586,-0.487233,-0.302303,-1.122148,-1.609933,1.112233,0.003725,0.227691,-0.097546,0.251634,-0.267663,-1.741361,2.035584,1.023216,0.780566,-0.317958,-1.216311,0.112640,-0.288304,-0.195169,-0.155590,-0.134919,-0.068105,0.558267,-0.064357,0.293176,-2.034930,0.921312,0.018867,-1.211018,0.214061,-0.005096,-0.580580,0.097598,0.399444,-0.101924,0.781219,-1.234648,-0.485580,-0.064926,0.163937,0.475265,-0.483969,-0.542673,0.360530,0.294616,-0.694417,0.386683,0.213087,8.598022,-1.642198,-1.280517,-0.449836,-0.139926,0.448851,0.252857,0.153518,-0.666207,-0.307773,-0.117375,0.588715,-0.271389,0.166913,-0.021357,-0.393928,24.0,1

In [44]:
np.isnan(x[:, 0])

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

## Dev

In [61]:
def get_data_for_ddh(df):
    ids = df['id'].unique()
    X_list = []
    Y_list = []
    D_list = []
    for id in ids:
        df_id = df[df['id'] == id]
        X = df_id.drop(columns=["event", "event_at_time", "time", "start", "stop", "id", "split", "subsplit"]).values
        Y = (df_id['time'] - df_id['stop']).values
        # convert Y to int (number of days) to be compatible with the discretization step
        Y = Y.astype(int)
        D = df_id['event_at_time'].values
        X_list.append(X)
        Y_list.append(Y)
        D_list.append(D)
    return X_list, Y_list, D_list, ids

def discretize(t, split, split_time=None):
    """
        Discretize the survival horizon

        Args:
            t (List of Array): Time of events
            split (int): Number of bins
            split_time (List, optional): List of bins (must be same length than split). Defaults to None.

        Returns:
            List of Array: Disretized events time
    """
    if split_time is None:
        _, split_time = np.histogram(np.concatenate(t), split - 1)
    t_discretized = np.array([np.digitize(t_, split_time, right = True) - 1 for t_ in t], dtype = object)
    return t_discretized, split_time

def get_padded_features(x):
    """Helper function to pad variable length RNN inputs with nans."""
    d = max([len(x_) for x_ in x])
    padx = []
    for i in range(len(x)):
        pads = np.nan*np.ones((d - len(x[i]),) + x[i].shape[1:])
        padx.append(np.concatenate([x[i], pads]))
    return np.array(padx)

In [65]:
X_train_list, Y_train_list, D_train_list, ids_train = get_data_for_ddh(ftpred_train)
X_val_list, Y_val_list, D_val_list, ids_val = get_data_for_ddh(ftpred_val)
X_test_list, Y_test_list, D_test_list, ids_test = get_data_for_ddh(ftpred_test)

In [67]:
max([len(x) for x in X_train_list]), max([len(x) for x in X_val_list]), max([len(x) for x in X_test_list])

(33, 31, 33)

In [56]:
X_train_padded = torch.from_numpy(get_padded_features(X_train_list)).type(torch.float32).to(device)
last_Y_train = torch.tensor([_[-1] for _ in Y_train_list]).type(torch.float32).to(device)
D_train = torch.tensor([_[-1] for _ in D_train_list]).type(torch.float32).to(device)

In [59]:
len(last_Y_train), last_Y_train, ids_train[0]

(103,
 tensor([3., 1., 1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 2., 4., 1., 5., 1., 1.,
         1., 1., 1., 4., 1., 1., 1., 1., 1., 1., 1., 3., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 3., 1., 1., 1., 2., 1., 1.,
         2., 2., 3., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1., 2., 1., 1., 1., 1.,
         1., 1., 1., 1., 2., 1., 1., 3., 1., 1., 2., 1., 1.]),
 2247)

In [60]:
ftpred_train[ftpred_train['id'] == ids_train[0]]

,id,start,stop,event,split,subsplit,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_12,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,feature_25,feature_26,feature_27,feature_28,feature_29,feature_30,feature_31,feature_32,feature_33,feature_34,feature_35,feature_36,feature_37,feature_38,feature_39,feature_40,feature_41,feature_42,feature_43,feature_44,feature_45,feature_46,feature_47,feature_48,feature_49,feature_50,feature_51,feature_52,feature_53,feature_54,feature_55,feature_56,feature_57,feature_58,feature_59,feature_60,feature_61,feature_62,feature_63,feature_64,feature_65,feature_66,feature_67,feature_68,feature_69,feature_70,feature_71,feature_72,feature_73,feature_74,feature_75,feature_76,feature_77,feature_78,feature_79,feature_80,feature_81,feature_82,feature_83,feature_84,feature_85,feature_86,feature_87,feature_88,feature_89,feature_90,feature_91,feature_92,feature_93,feature_94,feature_95,feature_96,feature_97,feature_98,feature_99,feature_100,feature_101,feature_102,feature_103,feature_104,feature_105,feature_106,feature_107,feature_108,feature_109,feature_110,feature_111,feature_112,feature_113,feature_114,feature_115,feature_116,feature_117,feature_118,feature_119,feature_120,feature_121,feature_122,feature_123,feature_124,feature_125,feature_126,feature_127,feature_128,feature_129,feature_130,feature_131,feature_132,feature_133,feature_134,feature_135,feature_136,feature_137,feature_138,feature_139,feature_140,feature_141,feature_142,feature_143,feature_144,feature_145,feature_146,feature_147,feature_148,feature_149,feature_150,feature_151,feature_152,feature_153,feature_154,feature_155,feature_156,feature_157,feature_158,feature_159,feature_160,feature_161,feature_162,feature_163,feature_164,feature_165,feature_166,feature_167,feature_168,feature_169,feature_170,feature_171,feature_172,feature_173,feature_174,feature_175,feature_176,feature_177,feature_178,feature_179,feature_180,feature_181,feature_182,feature_183,feature_184,feature_185,feature_186,feature_187,feature_188,feature_189,feature_190,feature_191,time,event_at_time
0,2247,0.0,1.0,0,train,train,-0.068892,0.434450,-0.475962,-0.606508,-1.107826,-0.516562,-1.426366,0.924110,0.315815,-0.290152,0.467812,-0.617799,0.011929,0.252888,-0.596915,-2.849330,-0.217827,-0.302398,-0.464257,-1.775085,-0.320602,0.488962,0.287560,0.725694,0.648309,0.507853,0.326476,0.390315,0.444491,-1.348959,-0.185466,-0.416936,-0.906970,2.383559,-0.072003,0.112769,1.149105,-0.427800,-0.142462,-0.311258,-0.000711,-0.463965,0.156178,-0.153701,0.546417,-0.743221,-0.392014,0.522309,0.502649,-0.439763,-0.502359,-0.240684,-0.155769,0.510055,-1.249786,-0.208171,-0.649825,-1.271306,0.293010,-0.122519,0.425848,-0.656036,-1.035086,0.024229,-0.415100,0.247042,0.736095,0.457277,1.118314,-0.138723,0.603962,-0.034964,1.124289,-0.190289,-1.545760,-0.392904,-0.180932,1.205222,1.606579,1.354515,0.790959,-0.042253,0.043080,-0.538366,-0.282173,-0.090835,0.142220,0.532247,0.345122,-0.325657,-0.896765,0.117699,0.725369,-0.416583,-0.971546,-0.040033,1.464501,0.603989,1.123547,-0.499343,-0.098019,-0.428140,0.989843,-0.371760,0.552297,0.497693,-1.010880,0.157130,-0.293085,0.245201,-0.332840,0.536084,-0.582569,-0.604443,0.712304,-0.183913,0.283048,0.711450,-0.356052,-0.125031,-0.060907,-0.543221,0.496483,-0.380315,-0.635010,-0.036659,0.059456,0.572905,0.005715,-0.704481,-0.274242,-1.866201,1.047939,0.329890,0.249523,0.297566,-0.600154,-0.381039,-1.452676,-1.021666,0.249725,-0.013913,0.199483,-0.499990,-0.072221,-0.370190,0.582528,-0.187887,0.454385,0.486713,-0.337155,-1.497586,-0.138716,-1.087387,-0.318607,-1.145454,-1.118870,0.556388,0.471356,-0.732965,0.355277,-0.643899,-0.403243,0.419948,-0.356891,0.862359,-0.191525,0.443402,0.466493,-0.576038,0.681238,0.377939,0.412992,0.011536,-0.091395,0.205965,9.901992,-0.355886,-0.866850,-0.393897,-0.288230,1.313411,0.041764,1.423958,0.524819,-0.328623,-0.417134,0.811602,-0.452318,-0.576654,-0.047882,0.395285,35.0,0
1,2247,1.0,2.0,0,train,train,-0.717001,0.220855,-1.223452,-0.179500,-0.808897,-1.077805,-1.336015,0.257365,-0.722389,-0.146704,0.563405,-0.334192,0.226545,0.530657,-0.843811,-2.032294,-0.304053,-0.313681,-0.496503,-1.068051,-0.202947,0.406830,-0.023849,0.535094,0.135429,0.475412,0.192433,-0.097791,1.196582,-1.098957,-0.471318,-0.291723,-0.410339,1.849719,-0.555330,0.114793,0.727206,-0.457571,-0.224443,-0.581863,0.480472,-0.576977,0.793992,-0.164734,0.131095,-0.623867,-0.053744,-0.427979,0.177386,-0.172219,-0.441008,-0.197504,-0.165824,-0.382235,-1.117448,0.276416,-0.523685,-0.512743,-0.079642,-0.158801,-0.654009,-0.616159,-0.490714,-0.340945,-0.067155,-0.074229,0.209070,-0.245588,1.073804,0.142481,0.492907,-0.361029,0.669569,0.205171,0.280137,1.118742,-0.137691,0.522233,1.865619,1.042860,0.801490,0.241039,-0.301661,-0.827377,-0.627668,-0.562636,0.734826,1.099021,0.458537,-0.773585,-0.474658,0.022075,0.565852,-0.269307,-1.199796,0.215035,1.748761,-0.043269,0.881726,-0.851839,0.469456,0.051965,0.750912,0.304742,1.196217,1.093974,-0.271917,-0.345449,-0.516488,0.222943,0.074896,0.428228,-0.308981,-0.383139,0.676804,-0.498367,0.479777,0.842400,0.133280,-0.206368,-0.306191,0.339053,0.272274,-0.211573,-0.294875,0.105247,-0.632950,0.483333,0.215709,-0.808862,-1.062912,-1.890046,0.574194,0.702411,0.356910,0.503599,-0.292838,-0.212069,-1.613549,-0.248654,-0.047126,-0.267881,-0.306299,-0.550974,-0.484585,-0.061039,1.107658,0.008921,-0.102992,0.262115,0.229179,-1.225505,0.343473,-0.579576,0.102610,-0.709508,-0.350399,0.088230,0.367253,-1.046256,-0.374953,0.183695,-0.606180,0.386982,0.054552,0.371508,-0.238172,0.347625,0.779522,-0.741001,0.359868,0.009226,0.813055,0.130396,-0.222624,0.296102,10.527724,-1.126358,-1.611939,0.217558,-0.305494,0.696388,-0.407239,0.793590,-0.073133,-0.289788,-0.196773,1.107303,-0.944761,-0.058083,0.102993,-0.078859,35.0,0
2,2247,2.0,3.0,0,train,train,-0.263348,0.303479,-0.918676,-0.392439,-0.879700,-0.781503,-1.255901,0.564914,0.400822,-0.234287,0.416643,-0.437310,-0.038832,0.167407,-0.748181,-3.197802,-0.451166,0.035956,-0.364591,-1.752061,-0.328480,0.475103,0.409276,0.450915,0.542860,0.679526,0.406566,0.190534,0.374117,-1.087977,-0.222218,-0.285588,-0.708703,1.888041,-0.119056,0.229274,0.893532,-0.568592,-0.206012,-0.446943,0.231803,-0.526115,0.553487,-0.340016,0.497036,-0.839560,-0.493206,0.247275,0.457468,-0.508879,-0.433910,-0.130110,-0.167351,0.034367,-0.927601,-0.361034,-0.160152,-1.027624,0.088303,0.088705,0.104379,-0.946570,-0.672495,-0.104312,-0.171619,0.039645,0.490565,0.113877,1.238630,-0.016717,0.801086,-0.108255,0.558274,-0.205482,-1.091204,0.070783,-0.095615,1.144874,1.716486,1.229409,0.880611,0.353063,-0.043196,-0.922158,-0.186884,-0.267610,0.483997,0.335198,0.542064,-0.756801,-0.844879,0.263588,0.546577,-0.265409,-1.238306,-0.068540,1.532813,0.331757,1.119287,-0.552460,0.336102,-0.334176,1.133708,-0.073406,0.998188,0.672545,-0.617232,-0.070972,-0.518303,-0.014192,-0.096196,0.531886,-0.456161,-0.594498,0.363557,-0.201170,0.309180,0.941494,0.175017,-0.187059,-0.003670,-0.405063,0.427317,-0.435693,-0.639893,0.489164,-0.171498,0.309716,0.014699,-0.928958,-0.400144,-2.211341,0.753526,0.539444,0.454346,0.351734,-0.432689,-0.327053,-1.949342,-0.862149,0.262447,0.237340,-0.211783,-0.862043,-0.162372,-0.175245,0.661588,-0.058003,0.097881,0.195997,-0.042387,-0.977972,-0.022347,-0.668385,-0.324137,-0.816110,-1.103547,0.643971,0.603913,-0.569546,-0.058193,-0.110749,-0.779779,0.363410,-0.110890,0.919518,-0.344650,0.190430,0.593651,-0.541073,0.280545,0.253234,0.468815,0.134229,-0.487871,0.050924,10.143761,-0.325607,-1.173190,0.016498,0.114143,1.110235,0.057042,1.287820,0.344738,-0.824365,-0.325366,1.067182,-0.314858,-0.459070,0.092862,0.424478,35.0,0
3,2247,3.0,4.0,0,train,train,-0.332103,0.431307,-0.862906,-0.554698,-1.210610,-0.708795,-1.497685,0.813009,-0.012032,-0.018277,0.658643,-0.500518,0.077240,0.515022,-0.757015,-2.174532,-0.670614,-0.438302,-0.424990,-1.483061,-0.098793,0.486185,0.496677,0.419077,0.439637,0.256994,0.318480,-0.037349,0.634984,-1.312833,-0.253808,-0.394735,-0.662961,1.813993,-0.823067,0.188032,0.905807,-0.574182,-0.467189,-0.469473,0.275770,-0.480886,0.434839,-0.083309,0.474365,-0.752760,-0.706760,0.244131,0.622523,-0.398464,-0.527278,-0.320272,-0.151150,-0.193221,-1.213860,-0.253736,-0.682894,-0.676480,0.265441,0.294298,0.072941,-0.805709,-0.939632,-0.028191,-0.180364,0.156025,0.547457,0.197327,1.305061,-0.077836,0.728280,-0.026203,0.647296,0.026415,-0.643137,0.524889,-0.329846,1.164034,1.624720,1.464824,0.683077,0.390690,0.033847,-0.823077,-0.123754,-0.194156,0.543673,0.697615,0.215648,-0.574967,-0.920605,0.137139,0.608993,-0.212842,-1.262425,0.181908,1.700356,0.339043,1.191302,-0.359981,0.016189,-0.271897,0.812609,0.275511,0.612794,0.688757,-0.603057,-0.242229,-0.645673,0.243870,-0.108240,0.512541,-0.537789,-0.825574,0.249378,-0.334307,0.486986,0.801898,0.199520,0.208599,-0.126511,0.103746,0.626052,-0.411869,-0.567756,0.188780,0.030466,0.706882,-0.083374,-0.558481,-0.334820,-2.109607,1.016038,0.398866,0.309925,0.062448,-0.628732,-0.188757,-1.824430,-0.821154,0.059623,0.042761,0.003942,-1.002764,-0.393283,-0.205293,1.079684,0.053806,0.286989,0.131705,0.003602,-1.833637,0.080990,-0.780467,-0.085321,-0.861791,-0.955811,0.414374,0.370160,-1.138582,-0.336042,-0.056514,-0.802548,0.115288,-0.291330,1.103329,-0.161286,0.508311,0.605705,-0.342129,0.272995,-0.012513,0.478839,0.135183,-0.383543,0.227345,10.075923,-0.684676,-1.317415,-0.183844,-0.311585,1.326210,-0.220094,1.243602,0.768744,-0.250556,-0.319306,0.972536,-0.478428,-0.342993,0.131308,0.365132,35.0,0
4,2247,4.0,7.0,0,train,train,-0.457872,0.643610,-1.109912,-0.527613,-1.161993,-0.853324,-1.861990,0.871819,-0.445282,0.140382,0.557849,-0.705521,0.216399,0.705868,-0.776322,-1.788551,-0.463163,-0.426956,-0.643634,-1.173014,-0.352682,0.332448,0.295609,0.506543,0.215165,0.360302,0.414237,0.258729,1.100274,-1.106760,-0.347667,-0.424817,-0.683829,1.970202,-1.011346,0.082775,1.016325,-0.297992,-0.203243,-0.183771,0.250889,-0.423025,0.595931,-0.180616,0.689085,-0.735305,-0.467380,0.144708,0.285987,-0.324858,-0.517019,-0.539927,-0.152469,-0.303647,-1.466371,-0.139826,-0.764608,-0.406096,0.073074,0.389422,-0.155189,-0.674510,-0.688207,-0.175109,-0.202200,0.087121,0.754886,-0.100164,1.034123,-0.212652,0.590208,-0.113125,0.825447,0.276369,-0.325245,0.791935,-0.305719,0.999753,1.571821,1.360768,0.775251,0.247687,-0.025973,-0.767043,-0.355563,-0.391109,0.472218,0.832877,0.171666,-0.591222,-0.459662,0.199856,0.471791,-0.421775,-1.539700,0.182115,1.769006,0.220784,0.961002,-0.298777,0.194430,-0.140318,0.667888,0.395622,0.822132,1.023898,-0.334268,-0.333851,-0.632290,0.275723,-0.091591,0.512833,-0.343865,-0.744719,0.295013,-0.270344,0.479814,0.830298,0.337254,-0.076472,0.002484,-0.104595,0.405939,-0.613981,-0.123145,0.106919,-0.159745,0.634646,-0.282219,-0.517992,-0.881469,-1.943888,1.250994,0.782213,0.529033,-0.061562,-0.635370,-0.400777,-1.886548,-0.516087,-0.114972,-0.227060,-0.017397,-0.890381,-0.531819,-0.219554,1.316368,-0.067698,0.119941,0.355133,0.197129,-1.630491,0.390698,-0.503696,-0.304652,-1.065979,-0.886887,0.463641,0.139269,-1.396299,-0.382367,0.016815,-0.782927,0.253313,-0.014746,0.722377,-0.260167,0.486500,0.545940,-0.523041,0.156004,0.091855,0.521660,-0.003950,-0.074623,0.315680,10.031436,-0.918014,-1.454298,0.014724,-0.283012,1.170183,-0.117416,1.153386,0.392975,-0.131262,-0.353377,0.893180,-0.718563,-0.281935,0.285350,0.186047,35.0,0
5,2247,7.0,8.0,0,train,train,0.095534,0.414280,-0.501918,-0.575590,-0.929408,-0.724534,-1.505989,0.513744,0.659122,-0.200145,0.303283,-0.557598,0.284999,0.188932,-0.231466,-3.395268,-0.284070,-0.517347,-0.637861,-1.685920,-0.519146,0.711559,0.559791,0.512693,0.614836,0.323584,0.456452,0.158941,0.084742,-1.182388,-0.254016,-0.294223,-0.768880,2.201452,0.077448,0.118748,0.847012,-0.691980,-0.339442,-0.045107,0.090347,-0.538886,0.151786,-0.187396,0.542929,-0.752464,-0.377483,0.540280,0.456492,-0.344675,-0.588317,-0.322545,-0.211188,0.454817,-1.496544,-0.346190,-0.502415,-1.202603,0.240744,0.190362,0.351999,-0.658544,-0.853132,-0.185052,-0.220767,0.505740,0.874775,0.681074,1.402292,0.017781,0.704968,-0.225428,0.777065,-0.073066,-1.882107,-0.155130,-0.232957,1.374328,1.397700,1.467042,0.625425,0.243673,0.288880,-0.367102,-0.078281,-0.167268,0.024933,0.594234,0.379542,-0.473450,-0.806164,0.079557,0.963430,-0.222584,-0.813351,0.002931,1.867619,0.582018,1.406265,-0.262559,-0.301548,-0.534229,1.028180,-0.473594,0.406603,0.297259,-1.210223,0.162267,-0.246533,0.098410,-0.376684,0.286721,-0.840675,-0.780945,0.633027,0.004224,0.397292,0.759886,-0.357623,-0.118069,-0.165687,-0.638816,0.496920,-0.122662,-0.802724,0.214298,-0.063242,0.347573,-0.178712,-0.756534,-0.452309,-1.711556,0.673929,0.348924,0.069520,0.330765,-0.520151,-0.138497,-1.625477,-0.645585,0.234359,0.002995,0.085575,-0.208251,0.034675,-0.253670,0.360448,-0.205605,0.335659,0.178177,-0.057480,-1.284471,-0.415243,-0.845676,-0.147467,-0.846383,-1.203506,0.627535,0.460683,-0.832774,0.454789,-0.521743,-0.135701,0.173570,-0.673529,1.101581,-0.174902,0.402875,0.505630,-0.706076,0.430040,0.508909,0.414881,-0.131138,-0.437896,0.157822,9.656413,-0.030088,-1.018508,-0.464311,-0.283434,1.600505,0.091973,1.445687,0.854292,-0.122182,-0.465421,0.733594,-0.521376,-0.915274,0.127429,0.409583,35.0,0
6,2247,8.0,9.0,0,train,train,0.027188,0.356952,-0.629225,-0.567204,-1.117985,-0.644327,-1.697666,0.694404,0.342989,-0.156377,0.136287,-0.643474,0.444910,0.359228,-0.423048,-2.971601,-0.340570,-0.616521,-0.574464,-1.884989,-0.500240,0.719563,0.599809,0.429116,0.671960,0.163894,0.469791,0.065829,0.358708,-1.241319,-0.295839,0.015483,-0.725243,2.504922,-0.162349,0.213608,0.971628,-0.444729,-0.255584,-0.240088,-0.002986,-0.410453,0.273150,-0.073253,0.548251,-0.775209,-0.650153,0.371581,0.548018,-0.318183,-0.472113,-0.427448,-0.219165,0.197879,-1.288273,-0.302900,-0.698719,-0.950507,0.271569,0.276988,0.349156,-0.812051,-0.923576,-0.006922,-0.422854,0.312500,0.963243,0.235618,1.239213,0.228318,0.591386,-0.160906,1.028926,-0.047349,-1.653013,-0.206917,-0.287312,1.111868,1.374328,1.528926,0.962456,0.348235,0.173375,-0.420302,-0.086299,-0.345365,0.431408,0.556484,0.412567,-0.053088,-0.850360,-0.083875,0.585520,-0.173423,-1.001522,0.021036,1.902472,0.649108,0.916143,-0.097323,-0.152579,-0.232135,0.874219,-0.127882,0.617975,0.389812,-1.046786,0.345614,-0.443598,0.339264,-0.278462,0.532367,-0.550911,-0.986068,0.584556,0.205288,0.408422,0.780256,-0.121657,0.002810,-0.096789,-0.617694,0.158653,-0.323440,-0.912102,0.216589,-0.081159,0.560425,-0.445067,-0.668236,-0.555511,-1.804238,0.686182,0.327254,0.109704,0.210453,-0.565552,-0.252896,-1.674052,-0.664525,-0.000198,0.188294,0.139020,-0.640114,-0.104422,-0.204888,0.579342,-0.479623,0.402795,0.096641,-0.189249,-1.289434,-0.133617,-1.227665,-0.054079,-1.107940,-1.091847,0.717799,0.434294,-0.998304,0.250621,-0.308344,-0.534920,-0.138360,-0.493392,1.128020,-0.095033,0.418899,0.640647,-0.597716,0.567427,0.406573,0.427403,0.018910,-0.280732,0.343796,9.673496,-0.307164,-0.942438,-0.497305,-0.366813,1.512762,-0.114049,1.382878,1.005303,-0.202119,-0.452989,0.727837,-0.555615,-0.599229,0.195267,0.399890,35.0,0
7,2247,9.0,10.0,0,train,train,-1.273514,0.574268,-0.962366,-0.165176,-0.912034,-1.010404,-1.536326,0.615677,-0.459276,0.315897,0.608535,-1.068213,-0.077902,0.970885,-1.400033,-1.428543,-0.130067,-0.774075,-0.482801,-0.917111,0.204663,0.295745,0.470982,0.172168,0.417431,0.641093,0.208222,0.231555,1.250627,-1.461033,-0.119328,-0.571716,-0.541242,1.523744,-0.907497,0.211475,0.880758,-0.402898,-0.416971,-0.289864,0.282897,-0.365489,0.624398,-0.114464,0.218237,-0.739336,0.181092,-0.245425,0.430964,-0.301745,-0.593378,-0.172389,-0.455283,0.058921,-1.187970,0.002764,-0.560255,-0.420243,-0.084819,0.424046,-0.536325,-0.527139,-1.005880,-0.464721,-0.027040,0.353873,0.491258,0.056790,0.731142,0.180521,0.443564,0.010853,0.964788,0.406467,-0.231418,1.675619,-0.635731,0.854066,2.193327,1.140458,0.762172,0.004085,0.009469,-0.373951,-0.767390,-0.527364,0.697317,1.231756,0.296629,-0.754273,-0.621421,0.450927,0.486300,-0.578442,-1.330908,-0.194596,2.274940,-0.443710,1.125424,-0.654452,-0.254344,-0.045161,0.612160,-0.108605,0.672509,0.722238,-0.435632,-0.278528,-0.113645,0.407573,-0.142421,0.140098,-0.550341,-0.354231,0.585631,-0.779381,0.588969,0.536046,-0.515829,-0.259247,-0.329510,0.059278,0.720157,-0.507028,-0.062473,-0.292702,-0.673939,0.686481,0.319350,-0.461250,-1.158838,-1.274828,1.415178,0.557910,0.317455,0.135474,-0.012749,-0.561353,-1.207059,-0.561901,0.026653,0.069836,-0.147212,-0.416904,-0.412615,-0.029807,1.000612,0.413843,0.043257,0.280728,0.236651,-1.825850,0.412753,-0.452040,-0.034803,-0.990694,-0.342143,-0.161154,-0.001209,-1.193949,-0.173764,0.119223,-0.258211,0.444643,0.150543,-0.116502,0.076125,0.078578,0.182480,-0.456127,0.533700,-0.199265,0.547938,0.006207,0.008078,0.559026,10.157218,-0.897790,-1.046250,-0.177379,-0.345741,0.724434,-0.351015,1.054200,-0.550573,0.027214,-0.316170,0.459156,-1.305606,-0.019929,0.287820,0.350317,35.0,0
8,2247,10.0,14.0,0,train,train,-1.040699,0.568736,-0.979637,-0.238607,-0.806480,-1.129204,-1.734557,0.490589,-0.425110,0.330255,0.582453,-0.848630,0.254648,0.784978,-1.108763,-1.306994,-0.104109,-0.916370,-0.640739,-0.701585,-0.071988,0.228459,0.222556,0.497301,0.219472,0.539531,0.379874,0.202372,1.180228,-1.255904,-0.149320,-0.398574,-0.189828,1.464063,-0.940867,0.072200,0.963448,-0.353490,-0.233839,-0.473058,0.361960,-0.366483,0.998666,-0.175488,0.457718,-0.560922,-0.099564,-0.315622,0.009613,-0.241258,-0.530779,-0.187129,-0.383698,-0.090999,-1.288484,0.263083,-0.434110,-0.140338,-0.019527,0.268183,-0.285319,-0.507292,-0.763739,-0.289922,-0.064791,0.476592,0.286315,-0.377387,1.093480,-0.127765,0.434320,-0.081498,0.885665,0.578341,0.120081,1.735767,-0.561148,0.854043,1.491823,1.065871,0.888166,0.311177,-0.090117,-0.339370,-0.779258,-0.865674,0.371895,1.187250,0.336869,-0.486681,-0.380937,0.070704,0.716151,-0.638264,-1.515685,0.141744,1.933150,-0.344287,1.076516,-0.264193,-0.205781,-0.023441,0.639923,0.055076,0.666138,0.807218,-0.512948,-0.468753,-0.434274,0.471348,-0.287172,0.100165,-0.422214,-0.394242,0.415007,-0.525327,0.577812,0.650310,-0.362642,-0.317104,-0.341987,0.013555,0.230128,-0.745709,0.005228,0.037222,-0.497465,0.652376,0.227393,-0.381821,-1.233980,-1.090709,1.331786,0.497254,0.285478,0.127271,-0.322900,-0.618303,-1.617779,-0.207263,-0.001289,-0.014157,-0.355080,-0.811170,-0.582003,-0.102563,1.025323,0.417085,0.190358,0.467306,0.063226,-1.805839,0.196158,-0.529765,-0.027440,-0.651430,-0.555852,-0.113184,0.045505,-1.625529,-0.308200,0.290472,-0.371493,0.370425,-0.056250,-0.157914,0.023571,0.227045,0.232558,-0.715187,0.379449,0.038233,0.868968,0.016318,0.061145,0.524668,10.399523,-1.052163,-1.327236,-0.131129,-0.125628,0.874570,-0.355239,0.687736,-0.449314,0.313321,-0.405842,0.737419,-0.823341,-0.035216,0.311788,0.195702,35.0,0

In [47]:
idx = 10
X_train_list[idx].shape, Y_train_list[idx], D_train_list[idx]

((14, 192),
 array([18, 17, 16, 15, 14, 11, 10,  9,  8,  7,  4,  3,  2,  1]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

In [35]:
# manually specify the duration grid
Y_train_stacked_np = np.concatenate(Y_train_list)
D_train_stacked_np = np.concatenate(D_train_list)
print(Y_train_stacked_np.shape, D_train_stacked_np.shape)
mask = (D_train_stacked_np >= 1)  # boolean mask specifying which training points were not censored
duration_grid_train_np = np.unique(Y_train_stacked_np[mask])

# the `discretize` function allows us to supply it with a pre-specified grid
Y_train_discrete_np, _ = \
    discretize(Y_train_list,
                len(duration_grid_train_np) - 1,
                duration_grid_train_np)
duration_grid_train_np

(1907,) (1907,)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 35., 36.])

In [44]:
np.unique(np.concatenate(Y_test_list))

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.])

In [25]:
num_durations = 47
Y_train_discrete_np, duration_grid_train_np = discretize(Y_train_list, num_durations)
duration_grid_train_np

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47.])

In [37]:
output_num_durations = len(duration_grid_train_np)
print(f'Number of discretized durations to be used with Dynamic-DeepHit: {output_num_durations}')
print('Duration grid:', duration_grid_train_np)

Number of discretized durations to be used with Dynamic-DeepHit: 35
Duration grid: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 35. 36.]

In [40]:
Y_train_discrete_np.shape, len(Y_train_discrete_np[idx]), Y_train_discrete_np[idx]

((103,), 14, array([16, 15, 14, 13, 12,  9,  8,  7,  6,  5,  2,  1,  0, -1]))